name: apiproject_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^1.1.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  date_picker_plus: ^2.1.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/Gif/
    - assets/Img/


